name: Create Version of Reusable Workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:

  version-reusable-workflow:
    uses: .github/workflows/version-workflow.yaml